#ifndef MAINWINDOW_H
#define MAINWINDOW_H

#include <memory>

#include <QButtonGroup>
#include <QMainWindow>

class CS123XmlSceneParser;
class SupportCanvas3D;

namespace Ui {
    class MainWindow;
}

class DataBinding;

/**
 * @class MainWindow
 *
 * The main graphical user interface class (GUI class) for our application.
 */
class MainWindow : public QMainWindow {
    Q_OBJECT
public:
    MainWindow(QWidget *parent = 0);
    ~MainWindow();

protected:

    // Overridden from QWidget. Handles the window resize event.
    virtual void changeEvent(QEvent *e);

    // Overridden from QWidget. Handles the window close event.
    virtual void closeEvent(QCloseEvent *e);

private:

    // Helper function for checkAllRayFeatures() and uncheckAllRayFeatures(), either check or
    // clear all checkboxes associated with rendering features for Ray, depending on 'checked'.
    void setAllRayFeatures(bool checked);

    // Enables or disables the UI controls.
    void setAllEnabled(bool enabled);

    // Sets up the data bindings between the UI and app settings
    void dataBind();

    // [C++ Note] private members start with m_
    QList<DataBinding*> m_bindings;
    QList<QButtonGroup*> m_buttonGroups;
    SupportCanvas3D *m_canvas3D;
    std::unique_ptr<CS123XmlSceneParser> m_sceneParser;

    // EXCEPTION: 'ui' member which is auto-generated by Qt. DO NOT RENAME!
    Ui::MainWindow *ui;

    void updateRainUiEnabled();

    /**
     * @brief m_oldLength These are used to detect tree-specific changes.
     */
    float m_oldLength;
    float m_oldRadius;
    float m_oldAngle;
    float m_oldLeafSize;
    float m_oldLeafWidth;

    float m_oldLightCount;
    bool m_oldLightRand;

public slots:
    // Used internally to keep the aspect ratio up to date.
    void updateAspectRatio();

    // Used internally to keep data bindings and the user interface in sync.
    void settingsChanged();

    // Called when the user presses the "Render Image" button in the Ray panel
    void renderImage();
};

#endif // MAINWINDOW_H
